In [2]:
#Import Numpy
import numpy as np

#list
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(list1))

<class 'list'>


In [3]:
#Numpy arrray
list2 = np.array([1, 2, 3, 4])
print(list2)
print(type(list2))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
#Numpy multi-dimentional array
ndArray = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ndArray.shape)
print(list2.shape)

(2, 4)
(4,)


In [5]:
#Changing datatype
arrayTypechange = np.array([1, 2, 3, 4], dtype=float)
print(type(arrayTypechange[2]))

<class 'numpy.float64'>


In [6]:
#Inatilize arrays

#all 0
allZero = np.zeros((4, 5), dtype=int)
print(allZero)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
#all 1
allOne = np.ones((3, 3))

print(allOne)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#particular Value

# allTens = np.zeros((5, 5), dtype=int) + 10
#or

allTens = np.full((5, 5), 10)
print(allTens)


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [9]:
#Identity Matrix
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#random
r = np.random.random((2, 2))
print(r)

[[0.28148596 0.30782931]
 [0.00681443 0.8621143 ]]


In [11]:
#random int
ran = np.random.randint(10, 100, (3, 3))
print(ran)

[[30 13 62]
 [95 82 27]
 [23 33 57]]


In [13]:
#arrays of evenly spaced value
# spa = np.linspace(10, 30, 6) #Give the no of values
spa = np.arange(10, 30, 6) #Give the space
print(spa)

[10 16 22 28]


In [17]:
#Convert list to array
list = [1, 2, 3, 4]

npArr = np.asarray(list)
print(npArr)

<class 'list'>
[1 2 3 4]


In [21]:
#Analyzing NP array

c = np.random.randint(1, 100, (2, 3, 2))
print(c)

[[[ 3 79]
  [ 9 30]
  [67 30]]

 [[74 15]
  [30 41]
  [62 78]]]


In [25]:
#Array no of dimentions
print(c.ndim)

#Array dimentions
print(c.shape)

3
(2, 3, 2)


In [26]:
#No of elements
print(c.size)

12


In [27]:
#Array datatype
print(c.dtype)

int32


In [35]:
#Mathematical operations in np array
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

print(a)
print(b)

[[1 1 8]
 [3 6 5]
 [1 9 4]]
[[13 18 14]
 [12 15 18]
 [12 19 12]]


In [36]:
#Add array/Matrix
print(a + b)
#or
print(np.add(a, b))

[[14 19 22]
 [15 21 23]
 [13 28 16]]
[[14 19 22]
 [15 21 23]
 [13 28 16]]


In [47]:
#Matrix Multiplication
print(a * b)
#or
print(np.multiply(a, b))

[[ 13  18 112]
 [ 36  90  90]
 [ 12 171  48]]
[[ 13  18 112]
 [ 36  90  90]
 [ 12 171  48]]


In [48]:
#Array Manupulation
c = np.random.randint(1, 10, (2, 3))
print(c.shape)
print(c)

(2, 3)
[[2 3 2]
 [8 4 6]]


In [49]:
#tranpose
# t = np.transpose(c)
#or
t = c.T
print(t.shape)
print(t)

(3, 2)
[[2 8]
 [3 4]
 [2 6]]


In [50]:
#reshaping array
a = np.random.randint(10, 20, (4, 5))
print(a)
print(a.shape)

[[13 19 15 10 10]
 [15 13 16 11 13]
 [12 14 13 12 10]
 [10 13 15 15 15]]
(4, 5)


In [54]:
b = a.reshape(2, 10)
print(b)

[[13 19 15 10 10 15 13 16 11 13]
 [12 14 13 12 10 10 13 15 15 15]]
